#!/bin/bash

#------------------------------------------------------------------------------
# Project Name      - Caja-Scripts/'Hide files'
# Author E-Mail     - munabedan@gmail.com
# Author GitHub     - https://github.com/munabedan
#------------------------------------------------------------------------------
#
# MIT License
#
# Copyright (c) 2018 Muna Bedan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#
#------------------------------------------------------------------------------

# Get the selected folder's URI
selected_folders_uri="$CAJA_SCRIPT_SELECTED_FILE_PATHS"

# .hidden file uri
hidden_file_uri="$CAJA_SCRIPT_CURRENT_URI"


# check if the .hidden file exists
if [ ! -f "$hidden_file_uri/.hidden" ]; then
    # create the .hidden file
    touch "$hidden_file_uri/.hidden"
fi

# loop through the selected files and add them to the .hidden file
for file in $selected_folders_uri; do
    basename "$file" >> ".hidden"
done


# using zenity notify the user that the files are now hidden 

text="\n $selected_folders_uri \n\n Hit the reload button on the toolbar to hide the files."

zenity --info --title="Reload required" --text="$text"



